name: "Build From Flake"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Install Nix"
      uses: nixbuild/nix-quick-install-action@v26

    - name: "Restore/Cache Nix Store"
      id: cache
      uses: nix-community/cache-nix-action@v3
      with:
        key: cache-${{ runner.os }}-${{ hashFiles('flake.lok') }}

    - name: "Build CI dependencies"
      if: steps.cache.outputs.cache-hit != 'true'
      run: nix build .#ci

    - name: "Test cargo smart-release"
      run: nix develop --comand cargo smart-release
